/**
--TABLAS NECESARIAS:
UNIVERSO, SUPERHEROE 
--TABLA A RECORRER: 
UNIVERSO
--TABLA A RECORRER PARA EL DETALLE: 
SUPERHEROE
**/
DECLARE
    --ALMACENAR LOS UNIVERSOS
    CURSOR C_UNIVERSOS IS SELECT COD_UNIVERSO, NOMB_UNIVERSO 
    FROM UNIVERSO;

    --ALMACENAR LOS SUPERHEROES DE UN UNIVERSO
    CURSOR C_SUPERHEROES (P_UNIVERSO NUMBER) IS  --P_UNIVERSO ES EL PARAMETRO PARA INDICAR EL UNIVERSO AL QUE PERTENECE EL SH.
     SELECT NOMB_HEROE, NOMB_REAL, COD_HEROE, FECHA_APARICION
    FROM SUPERHEROE
    WHERE COD_UNIVERSO = P_UNIVERSO;
    
    --VARIABLE PARA INDICADAR SI ESTA SELECCIONADO
    SELECCIONADO DETALLE_HEROES.SELECCIONADO%TYPE;
    --VARIABLE PARA ALMACENAR LA ANTIGUEDAD DEL HEROE
    ANTIGUEDAD NUMBER;
    --VARIABLE PARA ALMACENAR LA SUMA DE LA ANTIGUEDAD DE LOS HEROES
    SUMA_ANTIGUEDAD NUMBER;
    --VARIABLE PARA ALMACENAR EL TOTAL DE HEROES SELECCIONADOS
    TOTAL_SELECCIONADOS NUMBER;
    --VARIABLE PARA ALMACENAR EL PROMEDIO DE LA ANTIGUEDAD DE LOS HEROES
    PROMEDIO NUMBER;

BEGIN
    --BORRAR LOS REGISTROS DE LAS TABLAS
    EXECUTE IMMEDIATE 'TRUNCATE TABLE RESUMEN_UNIVERSO';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE DETALLE_HEROES';
    --RECORRE LOS UNIVERSOS
    FOR reg_universo IN C_UNIVERSOS LOOP
        --INICIALIZA LAS VARIABLES
        TOTAL_SELECCIONADOS := 0;
        SUMA_ANTIGUEDAD := 0;
            --RECORRE LOS HEROES DEL UNIVERSO
            FOR reg_heroe IN C_SUPERHEROES(reg_universo.COD_UNIVERSO) LOOP
                --VERIFICAR LOS HEROES DEL UNIVERO
                IF REG_HEROE.NOMB_REAL IS NOT NULL THEN
                    SELECCIONADO := 'SI';
                        --CALCULAR LA ANTIGUEDAD DEL HEROE
                        ANTIGUEDAD := TRUNC(MONTHS_BETWEEN(SYSDATE, REG_HEROE.FECHA_APARICION)/12); 
                        SUMA_ANTIGUEDAD := SUMA_ANTIGUEDAD + ANTIGUEDAD;
                        --CUENTA LOS SELECCIONADOS
                        TOTAL_SELECCIONADOS := TOTAL_SELECCIONADOS + 1;
                ELSE
                    SELECCIONADO := 'NO';
                END IF;
                --INSERTAR RESULTADOS
                INSERT INTO DETALLE_HEROES VALUES (reg_universo.COD_UNIVERSO, REG_HEROE.COD_HEROE, REG_HEROE.NOMB_HEROE, SELECCIONADO);
            END LOOP;
            IF TOTAL_SELECCIONADOS > 0 THEN
                PROMEDIO := SUMA_ANTIGUEDAD / TOTAL_SELECCIONADOS;
                ELSE
                PROMEDIO := 0;
            END IF;
            --INSERTAR RESULTADOS
            INSERT INTO RESUMEN_UNIVERSO VALUES (reg_universo.COD_UNIVERSO, reg_universo.NOMB_UNIVERSO, TOTAL_SELECCIONADOS, PROMEDIO);
    END LOOP;
END;