-- La siguiente linea la debes agregar solo si tienes Oracle 18c
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER S04_duoc IDENTIFIED BY duoc
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER S04_duoc QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO S04_duoc ;
GRANT "CONNECT" TO S04_duoc ;
ALTER USER S04_duoc DEFAULT ROLE "RESOURCE","CONNECT";
