DECLARE
    --ALMACENAMOS LOS VILLANOS A PROCESAR
    CURSOR c_villanos (p_MIN_MAL NUMBER, p_MAX_MAL NUMBER) IS
        SELECT COD_VILLANO, NOMB_VILLANO, NIVEL_MALDAD
        FROM VILLANO
        WHERE NIVEL_MALDAD BETWEEN p_MIN_MAL AND p_MAX_MAL;
        
    --ALMACENA EL MINIMO NIVEL DE MALDAD LEIDO DESDE TECLADO.
    MIN_MAL NUMBER:= &MIN_MAL;
    --ALMACENA EL MAXIMO NIVEL DE MALDAD LEIDO DESDE TECLADO.
    MAX_MAL NUMBER:= &MAX_MAL;
    --ALMACENA EL PUNTAJE TOTAL DE PODERES DE UN VILLANO.
    PUNTAJE_TOTAL NUMBER;
    --ALMACENA LA OBSERVACION DE UN VILLANO.
    OBSERVACION_VILLANO informe_villanos.observacion%type;
    --ALMACENA EL DETALLE DE NEMESIS DE UN VILLANO.
    DETALLE_NEMESIS informe_villanos.es_nemesis_de%TYPE;
BEGIN
    --SE ELIMINAN LOS REGISTROS DE LA TABLA INFORME_VILLANOS
    EXECUTE IMMEDIATE 'TRUNCATE TABLE INFORME_VILLANOS';

    --SE RECORREN LOS VILLANOS A PROCESSAR
    FOR reg_evil IN c_villanos(min_mal, max_mal) LOOP 
        --OBTENEMOS EL PUNTAJE TOTAL DE PODERES
        SELECT NVL(SUM(PUNTAJE),0) INTO puntaje_total
        FROM villano_poder a JOIN poder b ON (a.cod_poder = b.cod_poder)
        WHERE a.cod_villano = reg_evil.COD_VILLANO;

    --DETERMINAMOS LA OBSERVACION DE ACUERDO A LA REGLA DE NEGOCIO.
    observacion_villano := CASE
        WHEN puntaje_total > reg_evil.NIVEL_MALDAD THEN 'PUNTAJE TOTAL DE PODERES SUPERIOR A SU NIVEL DE MALDAD'
        WHEN puntaje_total <= reg_evil.NIVEL_MALDAD THEN 'PUNTAJE TOTAL DE PODERES ES IGUAL O INFERIOR A SU NIVEL DE MALDAD'
        WHEN puntaje_total = 0 THEN 'SIN PODERES'
        END;
    
    --DETERMINAMOS EL DETALLE DE NEMESIS DE ACUERDO A LA REGLA DE NEGOCIO.
        SELECT NVL(b.NOMB_HEROE, 'NO ES NÉMESIS DE NADIE') INTO DETALLE_NEMESIS
        FROM HEROE_VILLANO a
        JOIN SUPERHEROE b ON a.COD_HEROE = b.COD_HEROE
        WHERE a.COD_VILLANO = reg_evil.COD_VILLANO;
    
    --INSERTAMOS EL REGISTRO EN LA TABLA INFORME_VILLANOS
        INSERT INTO INFORME_VILLANOS VALUES (reg_evil.COD_VILLANO, reg_evil.NOMB_VILLANO, reg_evil.NIVEL_MALDAD, puntaje_total, observacion_villano, detalle_nemesis);

    END LOOP;
END;