-- La siguiente linea la debes agregar solo si tienes Oracle 18c
--ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER S01_duoc IDENTIFIED BY duoc
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER S01_duoc QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO S01_duoc ;
GRANT "CONNECT" TO S01_duoc ;
ALTER USER S01_duoc DEFAULT ROLE "RESOURCE","CONNECT";
